### ISSUE TITLE
Generation time distribution definition 

### ISSUE THREAD

**Issue by seabbs** [epiforecasts/nowcasting.example#1]
It looks like the generation time is defined as a log-normal here: 

https://github.com/epiforecasts/nowcasting.example/blob/7cb3cb40e02c64521de0b366c3c74505e7f10856/inst/reports/est_trunc_epinow2.Rmd#L157

`EpiNow2` only/currently (unless you have updated it) Gamma distributed generation times.

**Comment by sbfnk** [comment]
Good point, thanks!
